/**
 * Extracts Shopify admin design tokens from the polaris.js web-components
 * bundle (https://cdn.shopify.com/shopifycloud/polaris.js) and emits
 * registry/extend-shopify/ui/extend-shopify-tokens.css.
 *
 * The bundle's CSS references every semantic token as
 * `var(--t-<name>-<buildhash>, <fallback>)` — the fallbacks ARE the real
 * token values, so we mine those. Structural metrics (heights, paddings,
 * radii, shadows) were verified against live-rendered components and are
 * kept as reviewed constants below; re-verify them when Shopify ships a
 * visibly different admin.
 *
 * Usage: node scripts/extract-tokens.mjs [path-to-cached-polaris.js]
 */
import { writeFile, readFile } from "node:fs/promises";

const BUNDLE_URL = "https://cdn.shopify.com/shopifycloud/polaris.js";
const OUT_PATH = new URL(
  "../registry/extend-shopify/ui/extend-shopify-tokens.css",
  import.meta.url
);

const src = process.argv[2]
  ? await readFile(process.argv[2], "utf8")
  : await (await fetch(BUNDLE_URL)).text();

// --- semantic color tokens: var(--t-<name>-<hash>, <fallback>) ---
const tokens = new Map();
const re = /var\(\s*(--t-[a-z0-9-]+?)-\d+\s*,/g;
let m;
while ((m = re.exec(src))) {
  let i = re.lastIndex,
    depth = 1,
    val = "";
  while (i < src.length && depth > 0) {
    const c = src[i];
    if (c === "(") depth++;
    else if (c === ")" && --depth === 0) break;
    val += c;
    i++;
  }
  val = val.replace(/\\n/g, " ").trim().replace(/\s+/g, " ");
  // nested var() fallbacks reference other hashed tokens; rewrite to --es-
  val = val.replace(/var\(\s*--t-([a-z0-9-]+?)-\d+\s*,\s*/g, "var(--es-$1, ");
  const name = m[1].replace(/^--t-/, "");
  if (!tokens.has(name)) tokens.set(name, val);
}
if (tokens.size < 50) {
  throw new Error(
    `Only ${tokens.size} tokens extracted — bundle format may have changed`
  );
}

// --- reviewed constants (computed-style verified, 2026-07-22) ---
const constants = `
  /* Typography (desktop: min-width 48rem or fine pointer) */
  --es-font-family: "Inter", -apple-system, BlinkMacSystemFont, "San Francisco",
    "Segoe UI", Roboto, "Helvetica Neue", sans-serif;
  --es-font-size: 0.8125rem; /* 13px */
  --es-line-height: 1.25rem; /* 20px */
  --es-font-weight: 450;
  --es-font-weight-medium: 550;
  --es-font-weight-bold: 650;
  --es-letter-spacing: 0rem;
  --es-font-size-small: 0.75rem; /* 12px */
  --es-line-height-small: 1rem;

  /* Input field (s-text-field / s-search-field) */
  --es-input-height: 2rem; /* 32px */
  --es-input-padding-inline: 0.75rem; /* 12px */
  --es-input-gap: 0.5rem; /* 8px */
  --es-input-radius: 0.5rem; /* 8px */
  --es-input-border-width: 0.04125rem; /* 0.66px hairline */
  --es-input-border-width-active: 0.0625rem; /* 1px when focused */
  --es-focus-ring-width: 0.125rem; /* 2px */
  --es-focus-ring-offset: 0.0625rem; /* 1px */

  /* Overlay surfaces (s-popover) */
  --es-popover-radius: 0.75rem; /* 12px */
  --es-shadow-popover: 0 0.5rem 1.5rem -0.5rem rgba(0, 0, 0, 0.28),
    0 0.5rem 1rem -0.25rem rgba(0, 0, 0, 0.05),
    0 0.1875rem 0.375rem 0 rgba(0, 0, 0, 0.05),
    0 0.125rem 0.25rem 0 rgba(0, 0, 0, 0.05),
    0 0.0625rem 0.125rem 0 rgba(0, 0, 0, 0.05),
    0 0 0 0.0625rem rgba(0, 0, 0, 0.06);

  /* Icon */
  --es-icon-size: 1.25rem; /* 20px */
`;

const lines = [...tokens.entries()]
  .sort(([a], [b]) => a.localeCompare(b))
  .map(([name, val]) => `  --es-${name}: ${val};`)
  .join("\n");

const css = `/* GENERATED by scripts/extract-tokens.mjs — do not edit by hand.
 * Semantic values mined from ${BUNDLE_URL}
 * Structural constants verified against live-rendered components.
 *
 * Font: Shopify admin uses InterVariable. Inside App Home it is provided by
 * the platform. Outside the admin, load:
 *   https://cdn.shopify.com/static/fonts/inter/v4/styles.css
 */
:root {
${constants}
  /* Semantic tokens (${tokens.size}) */
${lines}
}
`;

await writeFile(OUT_PATH, css);
console.log(`Wrote ${tokens.size} semantic tokens to ${OUT_PATH.pathname}`);
